### ISSUE TITLE
Remove dependency to isomemo/mpi-bpred

### ISSUE THREAD

**Issue by wahani** [Pandora-IsoMemo/bpred#2]
**Issue**

We have a dependency in the code to a private repository in the @isomemo account. I assume it is used to download some model-objects. Access is handled with an ssh key, which is and should remain a secret. This is blocking us from giving users the option to run the shiny app on local infrastructure.

**Goal**

Make it possible to run the shiny app locally without any configuration.

**Place in the code**

https://github.com/Pandora-IsoMemo/bpred/blob/8e9836d67494748dcbe74c849170c299771a730b/inst/app/server.R#L618

**Resolution 1**
- (optional) switch to git API from R, should be more solid solution
- (optional) switch to an S3 Bucket with public read access, even more solid and preferred although unnecessary if current solution is working
- security check of isomemo/mpi-bpred (credentials in git-history, other confidential data)
- make isomemo/mpi-bpred public 
- Remove and test access without key
- make the Docker-Image of the Shiny-App public in this repo
- change Jenkins build to take changes into account
- Estimate: 1 day without optionals

**Resolution 2**
- Make the use of the remote repository and model objects optional in the app
- Process unclear, needs further investigation, not preferred
- Estimate: tbd

**Comment by arunge** [comment]
@isomemo Currently, models that can be uploaded (1) into the app

![image](https://user-images.githubusercontent.com/16759098/156145411-b5a18363-325a-4111-a721-fd6840f6f267.png)

are stored under: https://github.com/isomemo/mpi-bpred/tree/master/models which is not public.

We would suggest to create a folder in this new and public repo, where such model files can be saved. How was your workflow in order to save an object into this place: https://github.com/isomemo/mpi-bpred/tree/master/models ?
Did you just commit the object, e.g. `2020-04-15_18_59_33_bpred.zip` ?

**Comment by arunge** [comment]
The dependency was removed with https://github.com/Pandora-IsoMemo/bpred/pull/3/files#diff-028fb2908d3f11c3c35bcd4305417237a0bbce7f1e696ab983367fe7036a7193

And we can discuss the workflow for updating presaved model objects on Monday.
